### ISSUE TITLE
Liitä UnitConnection:iin mukaan TPR:stä tuleva ordering

### ISSUE THREAD

**Issue by luopio** [kooditiimi/smbackend#1]
> tprekissä on datassa connections-avaimella lista/array dataa, jonka järjestys pitäisi huomioida
> nykyisellään connections-lista luetaan kyllä, mutta järjestys unohdetaan. Pieni homma, mutta
> hyvin pääsee alkuun tällä!

**Comment by jukvalim** [comment]
Suljettu, 9c7e46e8edb6109
